"""
tor_manager.py - Auto-detect, install, and manage the Tor daemon.

Provides a TorManager class that:
  - Checks if Tor is installed (looks for the binary)
  - Detects if Tor is already running
  - Installs Tor via the system package manager when missing
  - Starts Tor with a proper configuration (SOCKS + ControlPort)
  - Cleans up the Tor process on exit

A module-level helper stores the last created TorManager so callers
can stop the managed Tor daemon when the application exits.
"""

from __future__ import annotations

import os
import sys
import time
import json
import shutil
import signal
import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_SOCKS_PORT = 9050
DEFAULT_CONTROL_PORT = 9051

TORRC_TEMPLATE = """# Auto-generated by vimm-bulk-downloader
SOCKSPort 127.0.0.1:{socks_port}
ControlPort 127.0.0.1:{control_port}
CookieAuthentication 1
DataDirectory {data_dir}
Log notice file {log_path}
"""


# ---------------------------------------------------------------------------
# Module-level lifecycle tracker
# ---------------------------------------------------------------------------

#: Holds a reference to the most recently created TorManager so that
#: application shutdown code can call ``stop_managed_tor()``.
_managed_manager: Optional["TorManager"] = None


def stop_managed_tor():
    """Stop the Tor daemon that was started by any ``TorManager`` in this
    process, if it is still running.  Safe to call multiple times."""
    global _managed_manager
    if _managed_manager is not None:
        _managed_manager.stop()
        _managed_manager = None


# ---------------------------------------------------------------------------
# Platform helpers
# ---------------------------------------------------------------------------

def _install_command() -> list[str]:
    """Return the package-manager command to install Tor on this platform."""
    if sys.platform == "darwin":
        return ["brew", "install", "tor"]
    for pm, install_args in [
        ("apt-get", ["sudo", "apt-get", "install", "-y", "tor"]),
        ("apt", ["sudo", "apt", "install", "-y", "tor"]),
        ("dnf", ["sudo", "dnf", "install", "-y", "tor"]),
        ("yum", ["sudo", "yum", "install", "-y", "tor"]),
        ("pacman", ["sudo", "pacman", "-S", "--noconfirm", "tor"]),
        ("zypper", ["sudo", "zypper", "install", "-y", "tor"]),
    ]:
        if shutil.which(pm):
            return install_args
    return ["brew", "install", "tor"]


def _start_command(torrc_path: str) -> list[str]:
    tor_bin = shutil.which("tor") or "tor"
    return [tor_bin, "-f", torrc_path]


# ---------------------------------------------------------------------------
# TorManager
# ---------------------------------------------------------------------------

class TorManager:
    """Auto-manage the Tor daemon lifecycle.

    Usage::

        mgr = TorManager()
        if mgr.ensure_running():
            # Tor is ready …
        mgr.stop()   # cleanup on exit

    The last created ``TorManager`` is tracked at module level so
    ``stop_managed_tor()`` can be called from cleanup handlers.
    """

    def __init__(
        self,
        socks_port: int = DEFAULT_SOCKS_PORT,
        control_port: int = DEFAULT_CONTROL_PORT,
    ):
        self.socks_port = socks_port
        self.control_port = control_port
        self._process: Optional[subprocess.Popen] = None
        self._torrc_path: Optional[str] = None
        self._data_dir: Optional[str] = None
        self._log_path: Optional[str] = None
        self._started_by_us = False

        global _managed_manager
        _managed_manager = self

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    @staticmethod
    def is_installed() -> bool:
        """Check whether the ``tor`` binary exists on PATH."""
        return shutil.which("tor") is not None

    @staticmethod
    def is_running(port: int = DEFAULT_SOCKS_PORT) -> bool:
        """Check whether a Tor SOCKS proxy responds on *port*."""
        try:
            import requests
            resp = requests.get(
                "https://check.torproject.org/",
                proxies={
                    "http": f"socks5h://127.0.0.1:{port}",
                    "https": f"socks5h://127.0.0.1:{port}",
                },
                timeout=8,
            )
            return "Congratulations" in resp.text
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Installation
    # ------------------------------------------------------------------

    def install(self, interactive: bool = True) -> bool:
        """Install Tor via the system package manager.

        Returns True once Tor is installed.
        """
        if self.is_installed():
            return True

        cmd = _install_command()
        logger.info("Tor not found.  Install command: %s", " ".join(cmd))

        if interactive:
            print()
            print("Tor is not installed on this system.")
            print(f"  Install command: {' '.join(cmd)}")
            print()
            ans = input("  Install Tor now? [Y/n]: ").strip().lower()
            if ans == "n":
                logger.info("User declined Tor installation.")
                return False
            print(f"  Running: {' '.join(cmd)}")
            print("  (you may be prompted for your sudo password)")
            print()

        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120,
            )
            if proc.returncode == 0:
                logger.info("Tor installed successfully.")
                return True
            else:
                logger.error("Tor install failed:\n%s", proc.stderr)
                return False
        except subprocess.TimeoutExpired:
            logger.error("Tor install timed out after 120 seconds.")
            return False
        except FileNotFoundError:
            logger.error(
                "Package manager not found (%s).  Install Tor manually.",
                cmd[0],
            )
            return False
        except Exception as exc:
            logger.error("Tor install error: %s", exc)
            return False

    # ------------------------------------------------------------------
    # Startup
    # ------------------------------------------------------------------

    def start(self, wait_seconds: float = 15.0) -> bool:
        """Start the Tor daemon.

        Creates a temporary torrc, launches Tor as a subprocess (with
        stdout/stderr redirected to a log file so the pipe never blocks),
        and waits for the SOCKS port to become responsive.

        Returns True once Tor is ready.
        """
        if self.is_running(self.socks_port):
            logger.info("Tor is already running on port %d.", self.socks_port)
            return True

        # Unique data + log dirs so stale lock files never block restart
        session_id = str(int(time.time()))
        self._data_dir = os.path.join(
            tempfile.gettempdir(), f"vimm_bulk_downloader_tor_{session_id}"
        )
        self._log_path = os.path.join(
            tempfile.gettempdir(), f"vimm_bulk_downloader_tor_{session_id}.log"
        )
        os.makedirs(self._data_dir, exist_ok=True)

        # Write torrc
        torrc_content = TORRC_TEMPLATE.format(
            socks_port=self.socks_port,
            control_port=self.control_port,
            data_dir=self._data_dir,
            log_path=self._log_path,
        )
        fd, torrc_path = tempfile.mkstemp(prefix="vimm_torrc_", suffix=".txt")
        with os.fdopen(fd, "w") as fh:
            fh.write(torrc_content)
        self._torrc_path = torrc_path

        # Launch Tor (stdout -> log file so pipe never blocks)
        cmd = _start_command(torrc_path)
        logger.info("Starting Tor: %s", " ".join(cmd))

        try:
            self._process = subprocess.Popen(
                cmd,
                stdout=open(self._log_path, "a"),
                stderr=subprocess.STDOUT,
            )
        except FileNotFoundError:
            logger.error("Tor binary not found.  Is Tor installed?")
            self._cleanup_tempfiles()
            return False

        # Wait until Tor is ready
        deadline = time.time() + wait_seconds
        while time.time() < deadline:
            if self._process.poll() is not None:
                logger.error(
                    "Tor process exited prematurely (code %d).  See log: %s",
                    self._process.returncode,
                    self._log_path,
                )
                self._cleanup_tempfiles()
                self._process = None
                return False
            if self.is_running(self.socks_port):
                logger.info("Tor is ready (port %d).", self.socks_port)
                self._started_by_us = True
                return True
            time.sleep(0.5)

        logger.error("Tor did not become ready within %d s.  See log: %s",
                      wait_seconds, self._log_path)
        self.stop()
        return False

    # ------------------------------------------------------------------
    # High-level convenience
    # ------------------------------------------------------------------

    def ensure_running(self, interactive_install: bool = True) -> bool:
        """Install if needed, then start.  Returns True once ready."""
        if self.is_running(self.socks_port):
            return True
        if not self.is_installed():
            if not self.install(interactive=interactive_install):
                return False
        return self.start()

    # ------------------------------------------------------------------
    # Shutdown
    # ------------------------------------------------------------------

    def stop(self):
        """Stop the Tor daemon iff it was started by this manager."""
        if not self._started_by_us:
            self._cleanup_tempfiles()
            return

        if self._process:
            logger.info("Stopping Tor (PID %d)...", self._process.pid)
            try:
                self._process.send_signal(signal.SIGTERM)
                self._process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                logger.warning("Tor did not respond to SIGTERM, killing.")
                self._process.kill()
                self._process.wait()
            except Exception as exc:
                logger.warning("Error stopping Tor: %s", exc)
            self._process = None
            self._started_by_us = False
            logger.info("Tor stopped.")

        self._cleanup_tempfiles()

    def _cleanup_tempfiles(self):
        """Remove temporary torrc, data dir, and log."""
        for path in (self._torrc_path, self._log_path):
            if path and os.path.isfile(path):
                try:
                    os.remove(path)
                except Exception:
                    pass
        if self._data_dir and os.path.isdir(self._data_dir):
            try:
                shutil.rmtree(self._data_dir, ignore_errors=True)
            except Exception:
                pass
        self._torrc_path = None
        self._data_dir = None
        self._log_path = None

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.stop()


# ---------------------------------------------------------------------------
# Enable ControlPort in system torrc
# ---------------------------------------------------------------------------

def _torrc_path() -> Optional[str]:
    """Return the path to the system torrc file, or None if not found."""
    candidates = [
        "/etc/tor/torrc",
        "/opt/homebrew/etc/tor/torrc",
        "/usr/local/etc/tor/torrc",
        os.path.expanduser("~/.tor/torrc"),
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p
    return None


def control_port_reachable(port: int = DEFAULT_CONTROL_PORT) -> bool:
    """Check whether the Tor ControlPort is accessible on localhost."""
    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(2)
    try:
        result = sock.connect_ex(("127.0.0.1", port))
        return result == 0
    finally:
        sock.close()


def _tor_restart_command() -> list[str]:
    """Return command to restart the Tor service."""
    if sys.platform == "darwin":
        # Try brew first, fallback to launchctl
        if shutil.which("brew"):
            return ["brew", "services", "restart", "tor"]
        return ["sudo", "launchctl", "kickstart", "-k", "system/org.torproject.tor"]
    # Linux: try systemctl, then service
    if shutil.which("systemctl"):
        return ["sudo", "systemctl", "restart", "tor"]
    if shutil.which("service"):
        return ["sudo", "service", "tor", "restart"]
    return ["sudo", "systemctl", "restart", "tor"]


# ---------------------------------------------------------------------------
# Fix cookie authentication permissions
# ---------------------------------------------------------------------------

COOKIE_CANDIDATES = [
    "/run/tor/control.authcookie",
    "/var/lib/tor/control.authcookie",
    "/var/run/tor/control.authcookie",
    "/tmp/tor/control.authcookie",
    os.path.expanduser("~/.tor/control.authcookie"),
]


def _find_cookie_file() -> Optional[str]:
    """Return path to the Tor control auth cookie, or None."""
    for path in COOKIE_CANDIDATES:
        if os.path.isfile(path):
            return path
    return None


def _is_cookie_readable() -> bool:
    """Check if the Tor control auth cookie can be read by us."""
    path = _find_cookie_file()
    if path is None:
        return True  # no cookie file -> no permission issue
    return os.access(path, os.R_OK)


def fix_tor_cookie_auth() -> bool:
    """Make the Tor control auth cookie readable by the current user.

    On Linux, Tor runs as user ``debian-tor`` and creates the cookie
    file with ``0600`` permissions, so regular users can't read it.

    This function first tries ``sudo -n`` (non-interactive, no password
    prompt).  If that fails (e.g. because sudo needs a password), it
    prints a one-time fix command for the user to run manually and
    returns False — the download will continue without IP rotation.

    Returns True once the cookie file is readable.
    """
    if _is_cookie_readable():
        return True

    cookie_path = _find_cookie_file()
    if cookie_path is None:
        logger.error("Could not find Tor control auth cookie to fix.")
        return False

    # Try non-interactive sudo first (works if user has passwordless sudo)
    logger.info("Tor cookie file %s is not readable — attempting sudo -n chmod", cookie_path)
    try:
        proc = subprocess.run(
            ["sudo", "-n", "chmod", "o+r", cookie_path],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if proc.returncode == 0:
            if _is_cookie_readable():
                logger.info("Tor cookie permissions fixed successfully.")
                return True
            else:
                logger.error("sudo chmod claimed success but cookie is still not readable.")
                return False
    except subprocess.TimeoutExpired:
        logger.warning("sudo -n chmod timed out (passwordless sudo not configured).")
    except Exception as exc:
        logger.warning("sudo -n chmod failed: %s", exc)

    # Non-interactive sudo failed — print manual fix command
    logger.warning(
        "Could not auto-fix Tor cookie permissions.\n"
        "  To enable IP rotation, run this command in your terminal:\n"
        "    sudo chmod o+r %s\n"
        "  The download will continue without IP rotation for now.",
        cookie_path,
    )
    # Also print to stderr so the user sees it even if logging is filtered
    print(
        "\n[!] Tor cookie not readable — run this command to enable IP rotation:",
        file=sys.stderr,
    )
    print(f"    sudo chmod o+r {cookie_path}", file=sys.stderr)
    print()

    return False


def enable_control_port(
    port: int = DEFAULT_CONTROL_PORT,
    socks_port: int = DEFAULT_SOCKS_PORT,
) -> bool:
    """Enable the Tor ControlPort in the system torrc.

    - Finds the torrc file (``/etc/tor/torrc`` on Linux)
    - Adds or uncomments ``ControlPort`` and ``CookieAuthentication`` lines
    - Restarts the Tor service
    - Waits until the ControlPort is reachable

    Returns True once the ControlPort is accessible.
    """
    torrc = _torrc_path()
    if torrc is None:
        logger.error("Could not find torrc file to edit.")
        return False

    # Read current content
    try:
        with open(torrc, "r") as fh:
            lines = fh.readlines()
    except OSError as exc:
        logger.error("Cannot read %s: %s", torrc, exc)
        return False

    # Check if ControlPort is already configured
    has_control = any(
        line.strip() and not line.strip().startswith("#")
        and "ControlPort" in line
        for line in lines
    )
    has_cookie = any(
        line.strip() and not line.strip().startswith("#")
        and "CookieAuthentication" in line
        for line in lines
    )
    has_group_readable = any(
        line.strip() and not line.strip().startswith("#")
        and "CookieAuthFileGroupReadable" in line
        for line in lines
    )

    # If both already configured (but maybe port is different), still try
    if has_control and has_cookie:
        # Already has ControlPort configured
        if control_port_reachable(port):
            return True
        # Maybe the port is different — force-add anyway

    # Build new lines to append
    new_lines = []
    if not has_control:
        new_lines.append(f"ControlPort {port}\n")
    if not has_cookie:
        new_lines.append("CookieAuthentication 1\n")
    if not has_group_readable:
        new_lines.append("CookieAuthFileGroupReadable 1\n")

    if not new_lines:
        # Both exist but port still not reachable — need to change port
        new_lines.append(f"ControlPort {port}\n")
        new_lines.append("CookieAuthentication 1\n")
        new_lines.append("CookieAuthFileGroupReadable 1\n")

    # Write using sudo tee (or direct append if writable)
    try:
        # Try direct write first (unlikely for system file)
        with open(torrc, "a") as fh:
            fh.write("\n# Added by vimm-bulk-downloader\n")
            for line in new_lines:
                fh.write(line)
    except OSError:
        # Need sudo — use tee
        append_content = "\n# Added by vimm-bulk-downloader\n" + "".join(new_lines)
        try:
            proc = subprocess.run(
                ["sudo", "tee", "-a", torrc],
                input=append_content,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if proc.returncode != 0:
                logger.error("Failed to write to torrc: %s", proc.stderr)
                return False
        except Exception as exc:
            logger.error("Cannot modify %s: %s", torrc, exc)
            return False

    logger.info("Added ControlPort configuration to %s", torrc)

    # Restart Tor
    restart_cmd = _tor_restart_command()
    logger.info("Restarting Tor: %s", " ".join(restart_cmd))
    try:
        subprocess.run(restart_cmd, capture_output=True, text=True, timeout=30)
    except Exception as exc:
        logger.error("Failed to restart Tor: %s", exc)
        return False

    # Wait for the ControlPort to become reachable
    deadline = time.time() + 15
    while time.time() < deadline:
        if control_port_reachable(port):
            logger.info("ControlPort :%d is now reachable.", port)
            return True
        time.sleep(1)

    logger.error("ControlPort :%d did not become reachable after restart.", port)
    return False


def enable_control_port_and_fix_cookie(
    port: int = DEFAULT_CONTROL_PORT,
    socks_port: int = DEFAULT_SOCKS_PORT,
) -> bool:
    """Enable ControlPort in torrc, restart Tor, then fix cookie permissions.

    Combines ``enable_control_port`` (persistent torrc change) with
    ``fix_tor_cookie_auth`` (immediate ``sudo chmod o+r``) so that the
    current user can authenticate with the control port right away.
    """
    ok = enable_control_port(port=port, socks_port=socks_port)
    if not ok:
        return False
    fix_tor_cookie_auth()
    return True
