"""
tor_manager.py - Auto-detect, install, and manage the Tor daemon.

Provides a TorManager class that:
  - Checks if Tor is installed (looks for the binary)
  - Detects if Tor is already running
  - Installs Tor via the system package manager when missing
  - Starts Tor with a proper configuration (SOCKS + ControlPort)
  - Cleans up the Tor process on exit

A module-level helper stores the last created TorManager so callers
can stop the managed Tor daemon when the application exits.
"""

from __future__ import annotations

import os
import sys
import time
import json
import shutil
import signal
import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_SOCKS_PORT = 9050
DEFAULT_CONTROL_PORT = 9051

TORRC_TEMPLATE = """# Auto-generated by vimm-bulk-downloader
SOCKSPort 127.0.0.1:{socks_port}
ControlPort 127.0.0.1:{control_port}
CookieAuthentication 1
DataDirectory {data_dir}
Log notice file {log_path}
"""


# ---------------------------------------------------------------------------
# Module-level lifecycle tracker
# ---------------------------------------------------------------------------

#: Holds a reference to the most recently created TorManager so that
#: application shutdown code can call ``stop_managed_tor()``.
_managed_manager: Optional["TorManager"] = None


def stop_managed_tor():
    """Stop the Tor daemon that was started by any ``TorManager`` in this
    process, if it is still running.  Safe to call multiple times."""
    global _managed_manager
    if _managed_manager is not None:
        _managed_manager.stop()
        _managed_manager = None


# ---------------------------------------------------------------------------
# Platform helpers
# ---------------------------------------------------------------------------

def _install_command() -> list[str]:
    """Return the package-manager command to install Tor on this platform."""
    if sys.platform == "darwin":
        return ["brew", "install", "tor"]
    for pm, install_args in [
        ("apt-get", ["sudo", "apt-get", "install", "-y", "tor"]),
        ("apt", ["sudo", "apt", "install", "-y", "tor"]),
        ("dnf", ["sudo", "dnf", "install", "-y", "tor"]),
        ("yum", ["sudo", "yum", "install", "-y", "tor"]),
        ("pacman", ["sudo", "pacman", "-S", "--noconfirm", "tor"]),
        ("zypper", ["sudo", "zypper", "install", "-y", "tor"]),
    ]:
        if shutil.which(pm):
            return install_args
    return ["brew", "install", "tor"]


def _start_command(torrc_path: str) -> list[str]:
    tor_bin = shutil.which("tor") or "tor"
    return [tor_bin, "-f", torrc_path]


# ---------------------------------------------------------------------------
# TorManager
# ---------------------------------------------------------------------------

class TorManager:
    """Auto-manage the Tor daemon lifecycle.

    Usage::

        mgr = TorManager()
        if mgr.ensure_running():
            # Tor is ready …
        mgr.stop()   # cleanup on exit

    The last created ``TorManager`` is tracked at module level so
    ``stop_managed_tor()`` can be called from cleanup handlers.
    """

    def __init__(
        self,
        socks_port: int = DEFAULT_SOCKS_PORT,
        control_port: int = DEFAULT_CONTROL_PORT,
    ):
        self.socks_port = socks_port
        self.control_port = control_port
        self._process: Optional[subprocess.Popen] = None
        self._torrc_path: Optional[str] = None
        self._data_dir: Optional[str] = None
        self._log_path: Optional[str] = None
        self._started_by_us = False

        global _managed_manager
        _managed_manager = self

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    @staticmethod
    def is_installed() -> bool:
        """Check whether the ``tor`` binary exists on PATH."""
        return shutil.which("tor") is not None

    @staticmethod
    def is_running(port: int = DEFAULT_SOCKS_PORT) -> bool:
        """Check whether a Tor SOCKS proxy responds on *port*."""
        try:
            import requests
            resp = requests.get(
                "https://check.torproject.org/",
                proxies={
                    "http": f"socks5h://127.0.0.1:{port}",
                    "https": f"socks5h://127.0.0.1:{port}",
                },
                timeout=8,
            )
            return "Congratulations" in resp.text
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Installation
    # ------------------------------------------------------------------

    def install(self, interactive: bool = True) -> bool:
        """Install Tor via the system package manager.

        Returns True once Tor is installed.
        """
        if self.is_installed():
            return True

        cmd = _install_command()
        logger.info("Tor not found.  Install command: %s", " ".join(cmd))

        if interactive:
            print()
            print("Tor is not installed on this system.")
            print(f"  Install command: {' '.join(cmd)}")
            print()
            ans = input("  Install Tor now? [Y/n]: ").strip().lower()
            if ans == "n":
                logger.info("User declined Tor installation.")
                return False
            print(f"  Running: {' '.join(cmd)}")
            print("  (you may be prompted for your sudo password)")
            print()

        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120,
            )
            if proc.returncode == 0:
                logger.info("Tor installed successfully.")
                return True
            else:
                logger.error("Tor install failed:\n%s", proc.stderr)
                return False
        except subprocess.TimeoutExpired:
            logger.error("Tor install timed out after 120 seconds.")
            return False
        except FileNotFoundError:
            logger.error(
                "Package manager not found (%s).  Install Tor manually.",
                cmd[0],
            )
            return False
        except Exception as exc:
            logger.error("Tor install error: %s", exc)
            return False

    # ------------------------------------------------------------------
    # Startup
    # ------------------------------------------------------------------

    def start(self, wait_seconds: float = 15.0) -> bool:
        """Start the Tor daemon.

        Creates a temporary torrc, launches Tor as a subprocess (with
        stdout/stderr redirected to a log file so the pipe never blocks),
        and waits for the SOCKS port to become responsive.

        Returns True once Tor is ready.
        """
        if self.is_running(self.socks_port):
            logger.info("Tor is already running on port %d.", self.socks_port)
            return True

        # Unique data + log dirs so stale lock files never block restart
        session_id = str(int(time.time()))
        self._data_dir = os.path.join(
            tempfile.gettempdir(), f"vimm_bulk_downloader_tor_{session_id}"
        )
        self._log_path = os.path.join(
            tempfile.gettempdir(), f"vimm_bulk_downloader_tor_{session_id}.log"
        )
        os.makedirs(self._data_dir, exist_ok=True)

        # Write torrc
        torrc_content = TORRC_TEMPLATE.format(
            socks_port=self.socks_port,
            control_port=self.control_port,
            data_dir=self._data_dir,
            log_path=self._log_path,
        )
        fd, torrc_path = tempfile.mkstemp(prefix="vimm_torrc_", suffix=".txt")
        with os.fdopen(fd, "w") as fh:
            fh.write(torrc_content)
        self._torrc_path = torrc_path

        # Launch Tor (stdout -> log file so pipe never blocks)
        cmd = _start_command(torrc_path)
        logger.info("Starting Tor: %s", " ".join(cmd))

        try:
            self._process = subprocess.Popen(
                cmd,
                stdout=open(self._log_path, "a"),
                stderr=subprocess.STDOUT,
            )
        except FileNotFoundError:
            logger.error("Tor binary not found.  Is Tor installed?")
            self._cleanup_tempfiles()
            return False

        # Wait until Tor is ready
        deadline = time.time() + wait_seconds
        while time.time() < deadline:
            if self._process.poll() is not None:
                logger.error(
                    "Tor process exited prematurely (code %d).  See log: %s",
                    self._process.returncode,
                    self._log_path,
                )
                self._cleanup_tempfiles()
                self._process = None
                return False
            if self.is_running(self.socks_port):
                logger.info("Tor is ready (port %d).", self.socks_port)
                self._started_by_us = True
                return True
            time.sleep(0.5)

        logger.error("Tor did not become ready within %d s.  See log: %s",
                      wait_seconds, self._log_path)
        self.stop()
        return False

    # ------------------------------------------------------------------
    # High-level convenience
    # ------------------------------------------------------------------

    def ensure_running(self, interactive_install: bool = True) -> bool:
        """Install if needed, then start.  Returns True once ready."""
        if self.is_running(self.socks_port):
            return True
        if not self.is_installed():
            if not self.install(interactive=interactive_install):
                return False
        return self.start()

    # ------------------------------------------------------------------
    # Shutdown
    # ------------------------------------------------------------------

    def stop(self):
        """Stop the Tor daemon iff it was started by this manager."""
        if not self._started_by_us:
            self._cleanup_tempfiles()
            return

        if self._process:
            logger.info("Stopping Tor (PID %d)...", self._process.pid)
            try:
                self._process.send_signal(signal.SIGTERM)
                self._process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                logger.warning("Tor did not respond to SIGTERM, killing.")
                self._process.kill()
                self._process.wait()
            except Exception as exc:
                logger.warning("Error stopping Tor: %s", exc)
            self._process = None
            self._started_by_us = False
            logger.info("Tor stopped.")

        self._cleanup_tempfiles()

    def _cleanup_tempfiles(self):
        """Remove temporary torrc, data dir, and log."""
        for path in (self._torrc_path, self._log_path):
            if path and os.path.isfile(path):
                try:
                    os.remove(path)
                except Exception:
                    pass
        if self._data_dir and os.path.isdir(self._data_dir):
            try:
                shutil.rmtree(self._data_dir, ignore_errors=True)
            except Exception:
                pass
        self._torrc_path = None
        self._data_dir = None
        self._log_path = None

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.stop()
